version: '3'

services:
    networkstuff-mysql-db:
        image: mysql:8.0.32
        container_name: networkstuff-mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: networkstuff
            MYSQL_PASSWORD: 123456Aa@
            MYSQL_ROOT_HOST: '%'